#!/system/bin/sh

# --Torch script--
# Chainloads flashlight patch to gain access to /sys/class/leds/torch-light1/brightness
# Can be executed by entering the following into the android shell: torch
# Function : Toggles flashlight on and off

if [ $(cat /sys/class/leds/torch-light1/brightness) = "0" ]; then
  echo 1 > /sys/class/leds/torch-light1/brightness
elif [ $(cat /sys/class/leds/torch-light1/brightness) = "1" ]; then
  echo 0 > /sys/class/leds/torch-light1/brightness
fi
